In [6]:
import numpy as np

a = np.array([20,30,40,50])
b = np.arange(4)

print(a + b)
# [20 31 42 53]
print(a * b)
# [ 0 30 80 150] 自己對齊0123

print(a-2)
print(a/10)  #有小數點
print((a/10).astype(int)) #整數

[20 31 42 53]
[  0  30  80 150]
[18 28 38 48]
[2. 3. 4. 5.]
[2 3 4 5]


In [8]:
data = np.array([[1,2],[3,4],[5,6]])
onerow = np.array([1,1])

print(data+onerow)

[[2 3]
 [4 5]
 [6 7]]


In [16]:
a = np.array([10,20,30,40])
b = []
print(a+1)

for i in a:
    b.append(i+1)
print(b)

[11 21 31 41]
[11, 21, 31, 41]


In [28]:
a = np.array([[1.0,2.0],[3.0,4.0]])
y = np.array([[5.],[7.]])

print(a)
print(y)

a = a.transpose()
print(a)
a = np.linalg.inv(a)  
#matrix inverse
print(a)
print(np.trace(a))
print(np.linalg.solve(a,y))

[[1. 2.]
 [3. 4.]]
[[5.]
 [7.]]
[[1. 3.]
 [2. 4.]]
[[-2.   1.5]
 [ 1.  -0.5]]
-2.5
[[26.]
 [38.]]


In [39]:
np.sqrt(4)
a = np.array([[9,4],[4,16]])
np.sqrt(a)

np.e
np.exp(1)
np.exp(np.arange(5)) #e的次方(0~4)

np.log(9)/np.log(3)
#np.fix = 向0的方向取整數 特別
#np.rint(round的意思)朝近的方向整數

2.0

In [42]:
#簡答題1
a = np.array( [20,30,40,50] )
b = np.array( [1,2,3,4] ) 
c = 1
d = np.array( [1] )
e = np.array( [1,2] ) 
print(a)
print(b)
print(c)
print(d)
print(e)

[20 30 40 50]
[1 2 3 4]
1
[1]
[1 2]


In [43]:
#簡答題2
print((a+b)*(-a/2))

[ -210.  -480.  -860. -1350.]


In [55]:
#簡答題3
e1=np.array([1,0,0])
e2=np.array([1,0,0]) #.reshape(3,1)

print(np.dot(e1,e2))
print(np.cross(e1,e2))
#6*1的外積好像沒辦法用cross計算耶，因為6維空間無法定義?

1
[0 0 0]
