In [6]:
print(2 + 3)
print(2 - 3)
print(2 * 3)
print(10 / 2)
print(3 ** 2) # R 語言使用 3 ^ 2
print(10 % 4) # R 語言使用 10 %% 4

5
-1
6
5.0
9
2


In [9]:
print(type(5)) # <class 'int'>
print(type(5.5)) # <class 'float'>
print(type(5 + 3j)) # <class 'complex'>
print(type(True)) # <class 'bool'>
print(1.0 == True) # True
print(0 == False) # True
print(1.2 + True) # 2.2
print(3 + True * 2) # 5


<class 'int'>
<class 'float'>
<class 'complex'>
<class 'bool'>
True
True
2.2
5


In [11]:
my_bool = True
print(type(my_bool)) #<class 'bool'>
print(float(my_bool)) # 1.0
print(int(my_bool)) # 1
print(complex(my_bool)) # 1+0j
print(type(str(my_bool))) #<class 'str'>


<class 'bool'>
1.0
1
(1+0j)
<class 'str'>


In [17]:
participated_group = "Big Data" 
current_ttl_articles = 4
current_ttl_articles =(float(current_ttl_articles))

is_participating = True 
my_status = [participated_group, current_ttl_articles, 
is_participating] 
print(type(my_status[0])) 
print(type(my_status[1])) 
print(type(my_status[2]))
print(my_status)


<class 'str'>
<class 'float'>
<class 'bool'>
['Big Data', 4.0, True]


In [20]:
groupName = "FireDragon" 
members = 4 
is_participating = True 
# 建立 dictionary
my_status = { "group": groupName, "memberCount": 
members, "is_participating": is_participating } 
# 利用鍵值選擇元素
print(my_status["group"]) 
print(my_status["memberCount"]) 
print(my_status["is_participating"])


FireDragon
4
True


In [28]:
import numpy # 引用套件
ironmen = numpy.array([46, 8, 11, 11, 4, 56]) # 將 list 透過numpy 的 array 方法進行轉換
print("外觀=",ironmen) # 看看 ironmen 的外觀
print(type(ironmen)) # 看看 ironmen 的資料結構
articles = ironmen * 30

print(articles)


外觀= [46  8 11 11  4 56]
<class 'numpy.ndarray'>
[1380  240  330  330  120 1680]


In [44]:
import numpy as np

npArray=np.array([1,True])
print(npArray.dtype)

npArr2=np.array([1,'hello',False])
print(npArr2.dtype)

arr=[1,True,False,'hello']
print(type(arr))

my_2d_array = np.array([[1, True],
[0, False]])
print(my_2d_array)

my_2d_array = np.array([[1, True],
["zero", False]])
print(my_2d_array)


int32
<U11
<class 'list'>
[[1 1]
 [0 0]]
[['1' 'True']
 ['zero' 'False']]


In [45]:
my_np_array = np.array([1, 2, 3, 4])
print(my_np_array ** 2)
my_2d_array = np.array([[1, 3],
[2, 4]])
print(my_2d_array ** 2)


[ 1  4  9 16]
[[ 1  9]
 [ 4 16]]


In [46]:
ironmen = np.array([46, 8, 11, 11, 4, 56])
print(ironmen[0]) # 選出 Modern Web 組的鐵人數
print(ironmen > 10) # 哪幾組的鐵人數超過 10 人
print(ironmen[ironmen > 10]) # 超過 10 人的鐵人數

46
[ True False  True  True False  True]
[46 11 11 56]


In [47]:
ironmen_2d_array = np.array([[46, 11, 4],
[8, 11, 56]])
print(ironmen_2d_array.size) # 6
print(ironmen_2d_array.shape) # (2, 3)


6
(2, 3)


In [65]:
import pandas as pd
groups = ["Modern Web", "DevOps", "Cloud", "Big Data", 
"Security", "自我挑戰組"]
ironmen = [46, 8, 12, 12, 6, 58]

ironmen_dict = {"groups": groups,"ironmen": ironmen}

ironmen_df = pd.DataFrame(ironmen_dict)

print(ironmen_dict ,'\n')
print(ironmen_df) # 看看資料框的外觀
print(type(ironmen_df)) # pandas.core.frame.DataFrame

print("\n\n符合大於10的有\n",ironmen_df[ironmen_df.loc[:,"ironmen"] > 10]) # 選出鐵人數超過 10 的 data frame

{'groups': ['Modern Web', 'DevOps', 'Cloud', 'Big Data', 'Security', '自我挑戰組'], 'ironmen': [46, 8, 12, 12, 6, 58]} 

       groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
4    Security        6
5       自我挑戰組       58
<class 'pandas.core.frame.DataFrame'>


符合大於10的有
        groups  ironmen
0  Modern Web       46
2       Cloud       12
3    Big Data       12
5       自我挑戰組       58


In [61]:
my_2d_array = np.array([[1, 3],
[2, 4]
])
my_df = pd.DataFrame(my_2d_array, columns = ["col1", "col2"])
print(my_df)


   col1  col2
0     1     3
1     2     4


In [67]:
print(ironmen_df.shape) # 回傳列數與欄數
print("---")
print(ironmen_df.describe()) # 回傳描述性統計
print("---")
print(ironmen_df.head(4)) # 回傳前三筆觀測值
print("---")
print(ironmen_df.tail(3)) # 回傳後三筆觀測值
print("---")
print(ironmen_df.columns) # 回傳欄位名稱
print("---")
print(ironmen_df.index) # 回傳 index


(6, 2)
---
         ironmen
count   6.000000
mean   23.666667
std    22.393451
min     6.000000
25%     9.000000
50%    12.000000
75%    37.500000
max    58.000000
---
       groups  ironmen
0  Modern Web       46
1      DevOps        8
2       Cloud       12
3    Big Data       12
---
     groups  ironmen
3  Big Data       12
4  Security        6
5     自我挑戰組       58
---
Index(['groups', 'ironmen'], dtype='object')
---
RangeIndex(start=0, stop=6, step=1)
