In [18]:
import numpy as np
import matplotlib.pyplot as plt
import sympy

In [19]:
from sympy import *

In [50]:
#簡答題
print(list(a)) #只轉第一層
print(a.tolist()) #全部都轉list

[array([0, 1, 2, 3, 4]), array([5, 6, 7, 8, 9]), array([10, 11, 12, 13, 14])]
[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]


In [55]:
#作業2
a=np.arange(15).reshape(3,5)
print(a)
print(type(a))

print(a.ndim) #rank
print(a.shape) #形狀
print(a.size) #就是size
print(a.dtype) #int
print(a.itemsize) #complex32类型元素的itemsize值为4=(32/8)
print(a.data) #buffer

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
<class 'numpy.ndarray'>
2
(3, 5)
15
int32
4


In [59]:
b=np.random.randint(10,size=6)
print(b)
print(b.ndim) #rank
print(b.shape) #形狀
print(b.size) #就是size
print(b.dtype) #int
print(b.itemsize) #complex32类型元素的itemsize值为4=(32/8)
print(b.data) #buffer

[3 9 1 3 9 9]
1
(6,)
6
int32
4


In [62]:
c=np.random.randint(10,size=(3,4)) #3x4矩陣

print(c)
print(c.ndim)
print(c.shape)
print(c.size)
print(c.dtype)
print(c.itemsize)
print(c.data)

[[1 7 6 3]
 [1 1 4 0]
 [3 1 1 8]]
2
(3, 4)
12
int32
4


In [63]:
d=np.random.randint(10,size=(2,3,2)) #2份3x2矩陣

print(d)
print(d.ndim)
print(d.shape)
print(d.size)
print(d.dtype)
print(d.itemsize)
print(d.data)

[[[5 4]
  [5 5]
  [0 6]]

 [[6 4]
  [9 4]
  [5 5]]]
3
(2, 3, 2)
12
int32
4


In [64]:
e = np.random.randint(10,size=5)

print(e)
print(e.tolist())

[5 7 4 3 7]
[5, 7, 4, 3, 7]


In [85]:
#作業3
def tolist(*iterable):
    for it in iterable:
        return it.tolist()
    
print(tolist(a))
print(tolist(b))
print(tolist(c))

[[0, 1, 2, 3, 4], [5, 6, 7, 8, 9], [10, 11, 12, 13, 14]]
[3, 9, 1, 3, 9, 9]
[[1, 7, 6, 3], [1, 1, 4, 0], [3, 1, 1, 8]]


In [ ]:
#作業結束

In [32]:
np.linspace(1,5,num=9)

array([1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. ])