In [2]:
import numpy as np

#print(np.array([1,2,3])) #array[1,2,3]

#print(np.array([1,2,3.0]))# array([ 1.,  2.,  3.])

#print(np.array(list({0:123 , 1:456}.items())))# array([[  0 123]  [  1 456]])

#print(np.zeros((2,3)))
#print(np.ones((2,3)))
#print(np.full((2,3), 9))

#固定長度的等差序列
print(np.arange( 10, 30 , 5))  # 等差 = 5
# array([10, 15, 20, 25])

#固定區間的等差序列
print(np.linspace(0,2,3))  #(2-0+1)/3 = 1.
# array([0. 1. 2.])

#等比序列
print(np.logspace( 0,2,3))
# array([1. 10. 100.])   #log100 =3

#組固定大小的亂數：

from numpy.random import default_rng
rng =default_rng()
normal = rng.standard_normal((3,2))
random = rng.random((3,2))
integers = rng.integers(0,10,size=(3,2))
print(normal)
print(random) 
print(integers)


#NumPy 結構化陣列 (Structured Arrays)
dt = np.dtype({'names' :('name' , 'num1' , 'num2' , 'true') , 
                            'formats':((np.str_,5) , np.int32 , int , 'U3')
})

#b= np.genfromtxt ("structured.txt" , delimiter=',' , dtype=dt)
#error
#print(b)

[10 15 20 25]
[0. 1. 2.]
[  1.  10. 100.]
[[ 0.1774849  -0.27080373]
 [ 1.14501812  0.14099467]
 [-0.7658267  -0.14361385]]
[[0.11322573 0.28566332]
 [0.08180303 0.64907366]
 [0.45093464 0.11193624]]
[[0 6]
 [4 9]
 [5 1]]


In [35]:
z = np.zeros(4, dtype=int)
print(z)

data = np.zeros(4, 
                dtype={'names':('name','age','weight','hello'),
                      'formats':('U10','i4','f8','U10')})
print(data.dtype)

data['name']= 'amy'
data[1]['name'] = 'john'
data['age']=50
data[1]['age'] = 120
data['weight']=789
data['hello']='hello!'
print(data)
print(data['name'])
print(data[0])
print(data[1]['name'])
print(data[ data['age']>100 ]['name'])

[0 0 0 0]
[('name', '<U10'), ('age', '<i4'), ('weight', '<f8'), ('hello', '<U10')]
[('amy',  50, 789., 'hello!') ('john', 120, 789., 'hello!')
 ('amy',  50, 789., 'hello!') ('amy',  50, 789., 'hello!')]
['amy' 'john' 'amy' 'amy']
('amy', 50, 789., 'hello!')
john
['john']


In [52]:
dt = np.dtype({'names' :('name' , 'num1' , 'num2' , 'true') , 
            'formats':((np.str_,5) , np.int32 , int , 'U3')
})

c=np.zeros(3, dtype=dt)

#可以自訂名稱
name = ['Chloe', 'Charlotte', 'Clara']
num_1 = [11, 12, 13]
num_2 = [14, 15, 16]
check = ['Y', 'Y', 'N']

#統一設定成自定的
c['name'] = name
c['num1'] = num_1
c['num2'] = num_2
c['true'] = check

print(c)

#RecordArray 與 Structured Array 非常類似
c_rec = c.view(np.recarray)
print(c_rec.name)

[('Chloe', 11, 14, 'Y') ('Charl', 12, 15, 'Y') ('Clara', 13, 16, 'N')]
['Chloe' 'Charl' 'Clara']


In [93]:
#簡答題1
#zeros初始值都是0，empty初始值=e

#簡答題2 使用astype
q2 = np.array([1.,2.5,3.5,4])
print(q2)

print(q2.astype(int))

#簡答題3, 限制整數的範圍介於 m - n 之間？ 
#clip 直接裁剪
np.clip(q2,1,3)
#或是乾脆在random時就設置範圍 (4~10)
np.random.randint(4,10,6)

[1.  2.5 3.5 4. ]
[1 2 3 4]


array([5, 9, 8, 4, 9, 4])